### ISSUE TITLE
Problem with NodeMCU Lolin V3

### ISSUE THREAD

**Issue by blackpearlla** [john30/ebusd-esp#73]
After the Flash putty shows only cryptical data.

Whats happening here?

![image](https://user-images.githubusercontent.com/11446500/199670706-f7b115ab-976d-47d5-ab08-ac1b21531c01.png)

**Comment by mfalkvidd** [comment]
@blackpearlla would you mind sharing how this was resolved, in case someone else has a similar problem?

**Comment by blackpearlla** [comment]
> @blackpearlla would you mind sharing how this was resolved, in case someone else has a similar problem?

The issue is not resolved for me but it seems like the board has an defect... I will have a look when i get a new one.
